name: tictactoe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # Networking
  http: ^0.12.0+4
  dio: ^3.0.8
  data_connection_checker: ^0.3.4

  # State management
  flutter_bloc: ^3.2.0

  # Dependency Injection
  get_it: ^3.1.0

  # Navigation
  auto_route: ^0.2.2

  # Logging
  logger: ^0.8.3

  # Data classes & json serialization
  freezed_annotation: ^0.4.0
  json_serializable: ^3.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^4.1.1

  # Generators
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  auto_route_generator: ^0.2.2

  # Data classes
  freezed: ^0.5.1


# The following section is specific to Flutter.
flutter:
  uses-material-design: true