name: tictactoe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.3

  # Networking
  http: ^0.12.0+4
  dio: ^3.0.9
  data_connection_checker: ^0.3.4
  retrofit: ^1.3.1+1

  # State management
  flutter_bloc: ^3.2.0

  # Dependency Injection
  get_it: ^4.0.1
  injectable: ^0.3.0

  # Navigation
  auto_route: ^0.4.1

  # Logging
  logger: ^0.8.3

  # Data classes & json serialization
  freezed_annotation: ^0.7.1
  json_serializable: ^3.2.5

  # Storage
  shared_preferences: ^0.5.6+3

  flushbar: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^4.1.1

  # Generators
  build_runner: ^1.8.0
  injectable_generator: ^0.3.3
  auto_route_generator: ^0.4.0

  # Networking
  retrofit_generator: ^1.3.1+8

  # Data classes
  freezed: ^0.10.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lang/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
          style: normal
          weight: 400
        - asset: fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900