name: tictactoe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.3

  # Networking
  http: ^0.12.1
  dio: ^3.0.9
  stomp_dart_client: ^0.3.3
  data_connection_checker: ^0.3.4

  # Firebase
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_messaging: ^6.0.16

  # State management
  flutter_bloc: ^4.0.0

  # Dependency Injection
  get_it: ^4.0.2
  injectable: ^0.4.0+1

  # Navigation
  auto_route: ^0.5.0

  # Logging
  logger: ^0.9.1

  # Data classes & json serialization
  kt_dart: ^0.7.0+1
  freezed_annotation: ^0.7.1
  json_serializable: ^3.3.0

  # Storage
  shared_preferences: ^0.5.7+3

  # Date formatter
  intl: ^0.16.0

  flushbar: ^1.9.1

  flutter_svg: ^0.17.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^4.1.1

  # Generators
  build_runner: ^1.10.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.5.0

  # Data classes
  freezed: ^0.10.9

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lang/
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
          style: normal
          weight: 400
        - asset: fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900